#!/bin/bash
# ZK-SNARK Steganography Demo Runner
# Chạy tất cả demo và tạo báo cáo tổng hợp

echo "STARTING ZK-SNARK STEGANOGRAPHY DEMO SUITE"
echo "===================================="
echo "Started at: $(date)"
echo ""

# Set variables
DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="$DEMO_DIR/logs/demo_suite_$(date +%Y%m%d_%H%M%S).log"

# Create directories
mkdir -p "$DEMO_DIR/logs" "$DEMO_DIR/output" "$DEMO_DIR/debug" "$DEMO_DIR/doc"
echo "Demo Suite Log - $(date)" > "$LOG_FILE"

# Function to run demo and log
run_demo() {
    local demo_name="$1"
    local demo_script="$2"
    
    echo "📋 Running $demo_name..."
    echo "----------------------------------------"
    echo ""
    
    # Log to file
    echo "=== $demo_name - $(date) ===" >> "$LOG_FILE"
    
    # Run demo
    if python3 "$DEMO_DIR/$demo_script" 2>&1 | tee -a "$LOG_FILE"; then
        echo ""
        echo "SUCCESS $demo_name completed successfully!"
        echo ""
    else
        echo ""
        echo "ERROR $demo_name failed!"
        echo ""
    fi
    
    echo "----------------------------------------"
    echo ""
}

# Check Python and dependencies
echo "CHECKING Checking environment..."
echo "Python version: $(python3 --version)"
echo "Demo directory: $DEMO_DIR"
echo ""

# Check if test images exist
if [ -d "$DEMO_DIR/../examples/testvectors" ]; then
    image_count=$(find "$DEMO_DIR/../examples/testvectors" -name "*.png" -o -name "*.webp" | wc -l)
    echo "Found $image_count test images"
else
    echo "WARNING  Test images directory not found!"
fi
echo ""

# Run demos in sequence
echo "🎬 Starting demo sequence..."
echo ""

# 1. Step-by-step demo (quick and simple)
run_demo "Step-by-Step Demo" "step_by_step_demo.py"
sleep 2

# 2. Comprehensive demo (detailed with logging)
run_demo "Comprehensive Demo" "comprehensive_demo.py"
sleep 2

# 3. Performance benchmark (thorough testing)
echo "🔬 Running Performance Benchmark (this may take a while)..."
echo "⏳ Please wait..."
echo ""
run_demo "Performance Benchmark" "performance_benchmark.py"

# Generate summary report
echo "DATA Generating summary report..."
SUMMARY_FILE="$DEMO_DIR/doc/demo_suite_summary_$(date +%Y%m%d_%H%M%S).md"

cat > "$SUMMARY_FILE" << EOF
# ZK-SNARK Steganography Demo Suite Summary

**Generated:** $(date)  
**Demo Directory:** $DEMO_DIR

## Execution Summary

### Demos Run
1. SUCCESS Step-by-Step Demo (\`step_by_step_demo.py\`)
2. SUCCESS Comprehensive Demo (\`comprehensive_demo.py\`)  
3. SUCCESS Performance Benchmark (\`performance_benchmark.py\`)

### Generated Files

#### Documentation (\`doc/\`)
- Performance reports (JSON format)
- Benchmark results (JSON + CSV)
- Performance charts (PNG)
- This summary report

#### Outputs (\`output/\`)
- Stego images with embedded messages
- ZK proof files (if generated)
- Benchmark test images

#### Debug Information (\`debug/\`)
- Chaos embedding initialization data
- Message embedding debug info
- ZK proof verification results

#### Logs (\`logs/\`)
- Detailed execution logs
- Error traces (if any)
- Performance timing data

## File Locations

\`\`\`
Demo/
├── doc/           # FOLDER All results and reports here
├── output/        # 🖼️ Generated stego images and proofs
├── debug/         # CHECKING Debug information files
└── logs/          # NOTE Execution logs
\`\`\`

## Next Steps

1. **Review Results**: Check \`doc/\` folder for detailed reports
2. **Analyze Performance**: Open performance charts and CSV files
3. **Debug Issues**: Check \`logs/\` and \`debug/\` if needed
4. **Test Custom Images**: Add your own images to \`../examples/testvectors/\`

## Quick Analysis Commands

\`\`\`bash
# View latest performance report
cat doc/performance_report_*.json | jq '.summary'

# Check demo logs
tail -50 logs/demo_suite_*.log

# List generated files
find doc/ output/ debug/ -type f -name "*" | sort
\`\`\`

---
Generated by ZK-SNARK Steganography Demo Suite
EOF

echo "📄 Summary report saved to: $SUMMARY_FILE"
echo ""

# Final summary
echo "COMPLETED DEMO SUITE COMPLETED!"
echo "======================="
echo "Completed at: $(date)"
echo ""
echo "FOLDER Results location: $DEMO_DIR"
echo "DATA Summary report: $(basename "$SUMMARY_FILE")"
echo "NOTE Full log: $(basename "$LOG_FILE")"
echo ""
echo "Generated files:"
find "$DEMO_DIR/doc" "$DEMO_DIR/output" "$DEMO_DIR/debug" -type f -name "*" 2>/dev/null | sort | sed 's/^/  - /'
echo ""
echo "CHECKING To review results:"
echo "  cd $DEMO_DIR"
echo "  ls -la doc/ output/ debug/ logs/"
echo ""
echo "Happy analyzing! CHART"